### ISSUE TITLE
[Mania Feature Request] Per Lane Accuracy

### ISSUE THREAD

**Issue by qusteka** [KedamaOvO/RealTimePPDisplayer#49]
Would it be possible to retrieve a lane accuracy implementation for Osu!Mania?
Example:
lane keybinds S,D,J,K
S: n300g:n300 ratio
D: n300g:n300 ratio
J: n300g:n300 ratio
K: n300g:n300 ratio

That way mania players could track their fingers individual performance and work on improving it.

**Comment by MikiraSora** [comment]
I think it's hard(even impossiable) to implement your feture request :(
Because there is no effective way to get judement result for each finger.

But it's easy for osu! implement. lol

**Comment by qusteka** [comment]
I was thinking maybe you could just figure out which lane was activated and wait for the judgment window to be determined. Now you write into an array the amount of n300g, n300 etc. that happened. The rest is basic math.

Alternatively you could track keypresses and wait for judgement result and track the result in an array.

**Comment by MikiraSora** [comment]
Nonono maybe you misunderstand my meaning. I mean that currently we couldn't get data for each finger and ORTDP is just a timer to get osu! memory and then post these data to RTPP plugin to calculate pp&more.
And because of the latter reason we even cant get data in "**real**" real-time. 
But it's possiable to implement when player has finished and we could get replay data and reproduce them.

**Comment by qusteka** [comment]
I think i get what you mean. Guess I'm just going to endorse the feature in the osu forums then. Thanks for taking the time to consider my proposal.
