### ISSUE TITLE
I can not change my output window's content

### ISSUE THREAD

**Issue by Naexen** [KedamaOvO/RealTimePPDisplayer#68]
I followed the wiki to change it, and no matter what I reboot the game or the sync client it won't change at all.
![image](https://user-images.githubusercontent.com/22392009/93620024-fa59e100-fa0b-11ea-97a5-7d276f363f28.png)
![image](https://user-images.githubusercontent.com/22392009/93620086-0ba2ed80-fa0c-11ea-9027-5c7bf2de6591.png)

**Comment by KedamaOvO** [comment]
Type “plugins install config” and “config”. On 09/19/2020 00:07, Naexen Chen wrote: 
I followed the wiki to change it, and no matter what I reboot the game or the sync client it won't change at all.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OsuSync/RealTimePPDisplayer/issues/68",
"url": "https://github.com/OsuSync/RealTimePPDisplayer/issues/68",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
